### ISSUE TITLE
add corpus from fuzz test

### ISSUE THREAD

**Issue by ccl0326** [SatelliteApplicationsCatapult/tribble#46]
In fuzz-go, there is a feature, it can decision whether to add the data into corpus from ret code of fuzz test. I think it's a very useful feature.

**Comment by emilyselwood** [comment]
Interesting idea. We'll have to change the interface of the FuzzTest method to return an enum but can be done and could be useful. 

Thanks for the suggestion.

**Comment by emilyselwood** [comment]
@ccl0326 Do you mind if I include you on the contributor list? Github doesn't include bug reports by default but I think it worth noting every one who helps the project.

**Comment by ccl0326** [comment]
@wselwood Thanks.It's my pleasure.  :)
